//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox calcInput;
		
		protected System.Web.UI.WebControls.TextBox calcTotal;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.WebControls.Button button3;
		
		protected System.Web.UI.WebControls.Button button4;
		
		protected System.Web.UI.WebControls.Button button5;
		
		protected System.Web.UI.WebControls.Button button6;
		
		protected System.Web.UI.WebControls.Button button7;
		
		protected System.Web.UI.WebControls.Button button8;
		
		protected System.Web.UI.WebControls.Button button9;
		
		protected System.Web.UI.WebControls.Button button0;
		
		protected System.Web.UI.WebControls.Button @decimal;
		
		protected System.Web.UI.WebControls.Button clear;
		
		protected System.Web.UI.WebControls.Button add;
		
		protected System.Web.UI.WebControls.Button subtract;
		
		protected System.Web.UI.WebControls.Button multiply;
		
		protected System.Web.UI.WebControls.Button divide;
		
		protected System.Web.UI.WebControls.Button equal;
	}
}
